name: all
on:
  - push
  - pull_request

jobs:
  ubuntu-latest:
    uses: ./.github/workflows/ci.yml
    with:
      os: ubuntu-latest

  macos-latest:
    uses: ./.github/workflows/ci.yml
    with:
      os: macos-latest
