name: all
on:
  - push
  - pull_request

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: ./.github/workflows/ci.yml
        with:
          os: ${{ matrix.os }}