name: ci
on:
  - pull_request
  - push

jobs:
  build:
    name: ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ github.sha }}
          restore_keys: |
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --release

  test:
    name: ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ github.sha }}
          restore_keys: |
            ${{ runner.os }}-cargo-

      - name: Test
        run: cargo test --release